### ISSUE TITLE
Does app name be displayed correctly on Japanese environment ?

### ISSUE THREAD

**Issue by tsu-komiyama** [kinako4122/warikanchan#9]
First, Congratulations on your app release !  
I installed this app into my iPhone and then Application name has been displayed 'warikanchan'.  
I think that 'わりかんちゃん' is the correct application name on Japanese.

**Comment by kinako4122** [comment]
Hi, kykomi.
I really thank you. I'm sure that I could not do that without your support.
I'm very happy even though the rate of installation is low yet(;o;)
I understand truly what you said to me "It's not a goal but the start" lol
You are right. Actually, I notice the problem.
I think this is because my app is set in English. But I didn't know where to change it.
(I do remember I set JAPANESE as a primary language before submitting but sadly it does not working?! or do I need any other setting?!)

If you know, let me know~~^^

**Comment by kykomi** [comment]
You may find the answer to google `CFBundleDisplayName`.
https://www.google.co.jp/search?q=CFBundleDisplayName&oq=cfbundle&aqs=chrome.0.69i59j69i57j69i59l2.1246j0j1&sourceid=chrome&ie=UTF-8
The app name on Home screen is based on CFBundleDisplayName.
Try !
